// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPlsSEyURPrB-ZP_aLfckqOjYVY16Wc8',
    appId: '1:1035076894721:web:b021dd2a5d3a24ba8c0000',
    messagingSenderId: '1035076894721',
    projectId: 'audify-f9365',
    authDomain: 'audify-f9365.firebaseapp.com',
    storageBucket: 'audify-f9365.firebasestorage.app',
    measurementId: 'G-2RXBV6HQ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU404SI4O8Ee1md4mPEmRWB5AtcPUhq1Y',
    appId: '1:1035076894721:android:2defd214102615638c0000',
    messagingSenderId: '1035076894721',
    projectId: 'audify-f9365',
    storageBucket: 'audify-f9365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAPjaw1VyWaH8-J3UXsIYS1BWqMa8AbO0',
    appId: '1:1035076894721:ios:a840c88277796ec48c0000',
    messagingSenderId: '1035076894721',
    projectId: 'audify-f9365',
    storageBucket: 'audify-f9365.firebasestorage.app',
    iosBundleId: 'com.example.audify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAPjaw1VyWaH8-J3UXsIYS1BWqMa8AbO0',
    appId: '1:1035076894721:ios:a840c88277796ec48c0000',
    messagingSenderId: '1035076894721',
    projectId: 'audify-f9365',
    storageBucket: 'audify-f9365.firebasestorage.app',
    iosBundleId: 'com.example.audify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWPlsSEyURPrB-ZP_aLfckqOjYVY16Wc8',
    appId: '1:1035076894721:web:3201f77f706a26268c0000',
    messagingSenderId: '1035076894721',
    projectId: 'audify-f9365',
    authDomain: 'audify-f9365.firebaseapp.com',
    storageBucket: 'audify-f9365.firebasestorage.app',
    measurementId: 'G-4RY4YM0F3N',
  );
}
